### ISSUE TITLE
Problem while installing Ganil2Root

### ISSUE THREAD

**Issue by mustak21** [gypaos/Ganil2Root#1]
I followed the instructions given in the install file but while giving the `make distclean ` and `make` commands in libs directory I am getting the following errors

![screenshot from 2017-04-28 16-39-23](https://cloud.githubusercontent.com/assets/25579005/25526476/49170d88-2c31-11e7-871c-bf8cf4a4c97d.png)

From where do I get the file  GDataParameters.h and also the `make distclean` command seems not working.

**Comment by adrien-matta** [comment]
Hi,

I think you are using it with ROOT6 (dicttype error) and GRU is probably not installed as well (missing header).

I am currently working on a new version of ganil2root working with Root 6 and the latest version of GRU. It should be ready within the next 4 weeks.

**Comment by mustak21** [comment]
Yes I am using ROOT 6 and centos 7. I followed the steps while installing GRU and the three executables namely Ganil_Tape,GRU and vigru are also created in the bin folder inside the GRU directory.Is there any way that I can verify whether the GRU is installed properly or not?

**Comment by adrien-matta** [comment]
Hi,
I am not sure. I don't develop or maintain GRU, so I don't really have the upper hand on this. I am in contact with Luc, the GRU maintainer about having a ROOT 6 compatible version, and I think there is some progress, but I can't say anything more.
